### ISSUE TITLE
Setting Up set_left function

### ISSUE THREAD

**Issue by def-chuksy** [Chukwuyem/RustWork1#1]
I'm currently trying to set up a set left child node function. The problem is, in the definition of the struct Node, I have use
`left: Option<Box<Node>>`
Option because left could be Null or a Node and Box to avoid "recursive with indirection" error. 
In the set left function, what's happening basically a recreation of the struct instance except the left node is changed.
The current issue is the I have a problem reassigned the right node to itself.

**Comment by league** [comment]
I'll have to investigate, as time permits. But yes, let's use this thread to discuss our findings!
